-- Generated SQL Import Script from project_report.csv
BEGIN;
INSERT INTO tasks (title, description, type, category, date, month, year, time, assignee, assignees, status, color, priority, created_by) VALUES ('MICC Project Launch', 'Link: https://app.coschedule.com/calendar/413257/schedule/open/content/edit/7596523', 'Blog', 'blogPosts', 16, 9, 2026, '09:00', 4, ARRAY[4], 'planned', 'bg-red-100 text-red-800 border-red-200', 'medium', 1);
INSERT INTO tasks (title, description, type, category, date, month, year, time, assignee, assignees, status, color, priority, created_by) VALUES ('MICC Pilot Delivery (Exact Date TBD)', 'Link: https://app.coschedule.com/calendar/413257/schedule/open/content/edit/7592542', 'Blog', 'blogPosts', 8, 5, 2026, '09:00', 4, ARRAY[4], 'planned', 'bg-red-100 text-red-800 border-red-200', 'medium', 1);
INSERT INTO tasks (title, description, type, category, date, month, year, time, assignee, assignees, status, color, priority, created_by) VALUES ('Understanding PTSD module launch', 'Link: https://app.coschedule.com/calendar/413257/schedule/open/content/edit/7411151', 'Social', 'socialMedia', 7, 3, 2026, '09:00', 4, ARRAY[4], 'planned', 'bg-yellow-100 text-yellow-800 border-yellow-200', 'medium', 1);
INSERT INTO tasks (title, description, type, category, date, month, year, time, assignee, assignees, status, color, priority, created_by) VALUES ('(TENTATIVE 2) Launch: Canadian Legacy Project (women''s research) report', 'Link: https://app.coschedule.com/calendar/413257/schedule/open/content/edit/7593131', 'Strategy', 'strategicPlanning', 1, 3, 2026, '09:00', 4, ARRAY[4], 'planned', 'bg-red-100 text-red-800 border-red-200', 'medium', 1);
INSERT INTO tasks (title, description, type, category, date, month, year, time, assignee, assignees, status, color, priority, created_by) VALUES ('In her words - Daphne post', 'Link: https://app.coschedule.com/calendar/413257/schedule/open/content/edit/7632281', 'Social', 'socialMedia', 31, 2, 2026, '09:00', 4, ARRAY[4], 'planned', 'bg-yellow-100 text-yellow-800 border-yellow-200', 'medium', 1);
INSERT INTO tasks (title, description, type, category, date, month, year, time, assignee, assignees, status, color, priority, created_by) VALUES ('End-of-year survey reminder', 'Link: https://app.coschedule.com/calendar/413257/schedule/open/content/edit/6818805', 'Strategy', 'strategicPlanning', 17, 2, 2026, '09:00', 4, ARRAY[4], 'planned', 'bg-green-100 text-green-800 border-green-200', 'medium', 1);
INSERT INTO tasks (title, description, type, category, date, month, year, time, assignee, assignees, status, color, priority, created_by) VALUES ('In her words - Telah Morrison post', 'Link: https://app.coschedule.com/calendar/413257/schedule/open/content/edit/7632279', 'Social', 'socialMedia', 10, 2, 2026, '09:00', 4, ARRAY[4], 'planned', 'bg-yellow-100 text-yellow-800 border-yellow-200', 'medium', 1);
INSERT INTO tasks (title, description, type, category, date, month, year, time, assignee, assignees, status, color, priority, created_by) VALUES ('MESHA Military Culture Training (tentative)', 'Link: https://app.coschedule.com/calendar/413257/schedule/open/content/edit/7411154', 'Social', 'socialMedia', 9, 2, 2026, '09:00', 4, ARRAY[4], 'planned', 'bg-yellow-100 text-yellow-800 border-yellow-200', 'medium', 1);
INSERT INTO tasks (title, description, type, category, date, month, year, time, assignee, assignees, status, color, priority, created_by) VALUES ('End-of-year survey', 'Link: https://app.coschedule.com/calendar/413257/schedule/open/content/edit/6818799', 'Strategy', 'strategicPlanning', 3, 2, 2026, '09:00', 4, ARRAY[4], 'planned', 'bg-red-100 text-red-800 border-red-200', 'medium', 1);
INSERT INTO tasks (title, description, type, category, date, month, year, time, assignee, assignees, status, color, priority, created_by) VALUES ('(TENTATIVE 1) Canadian Legacy Project report launch', 'Link: https://app.coschedule.com/calendar/413257/schedule/open/content/edit/7601772', 'Strategy', 'strategicPlanning', 17, 1, 2026, '09:00', 4, ARRAY[4], 'planned', 'bg-red-100 text-red-800 border-red-200', 'medium', 1);
INSERT INTO tasks (title, description, type, category, date, month, year, time, assignee, assignees, status, color, priority, created_by) VALUES ('Atlas Navigator', 'Link: https://app.coschedule.com/calendar/413257/schedule/open/content/edit/7361885', 'Marketing', 'marketingOps', 5, 1, 2026, '09:00', 4, ARRAY[4], 'planned', 'bg-orange-100 text-orange-800 border-orange-200', 'medium', 1);
INSERT INTO tasks (title, description, type, category, date, month, year, time, assignee, assignees, status, color, priority, created_by) VALUES ('Veteran Family Summit wrap up', 'Would prefer Tuesday - ask the team

Link: https://app.coschedule.com/calendar/413257/schedule/open/content/edit/7636600', 'Marketing', 'marketingOps', 2, 1, 2026, '09:00', 4, ARRAY[4], 'planned', 'bg-yellow-100 text-yellow-800 border-yellow-200', 'medium', 1);
INSERT INTO tasks (title, description, type, category, date, month, year, time, assignee, assignees, status, color, priority, created_by) VALUES ('Veteran Family Summit', 'Link: https://app.coschedule.com/calendar/413257/schedule/open/content/edit/7251817', 'Social', 'socialMedia', 28, 0, 2026, '09:00', 4, ARRAY[4], 'planned', 'bg-yellow-100 text-yellow-800 border-yellow-200', 'medium', 1);
INSERT INTO tasks (title, description, type, category, date, month, year, time, assignee, assignees, status, color, priority, created_by) VALUES ('In her words - Connie Uetz post', 'Link: https://app.coschedule.com/calendar/413257/schedule/open/content/edit/7632278', 'Social', 'socialMedia', 26, 0, 2026, '09:00', 4, ARRAY[4], 'planned', 'bg-yellow-100 text-yellow-800 border-yellow-200', 'medium', 1);
INSERT INTO tasks (title, description, type, category, date, month, year, time, assignee, assignees, status, color, priority, created_by) VALUES ('Last call for RCMP dialogue session', 'Link: https://app.coschedule.com/calendar/413257/schedule/open/content/edit/7288455', 'Social', 'socialMedia', 20, 0, 2026, '09:00', 4, ARRAY[4], 'planned', 'bg-yellow-100 text-yellow-800 border-yellow-200', 'medium', 1);
INSERT INTO tasks (title, description, type, category, date, month, year, time, assignee, assignees, status, color, priority, created_by) VALUES ('Veteran Family Summit', 'Link: https://app.coschedule.com/calendar/413257/schedule/open/content/edit/7251806', 'Social', 'socialMedia', 19, 0, 2026, '09:00', 4, ARRAY[4], 'planned', 'bg-yellow-100 text-yellow-800 border-yellow-200', 'medium', 1);
INSERT INTO tasks (title, description, type, category, date, month, year, time, assignee, assignees, status, color, priority, created_by) VALUES ('Veteran Family Summit', 'Link: https://app.coschedule.com/calendar/413257/schedule/open/content/edit/7251805', 'Social', 'socialMedia', 13, 0, 2026, '09:00', 4, ARRAY[4], 'planned', 'bg-yellow-100 text-yellow-800 border-yellow-200', 'medium', 1);
INSERT INTO tasks (title, description, type, category, date, month, year, time, assignee, assignees, status, color, priority, created_by) VALUES ('MHCP Launch (Tentative)', 'Link: https://app.coschedule.com/calendar/413257/schedule/open/content/edit/6822755', 'Blog', 'blogPosts', 12, 0, 2026, '09:00', 4, ARRAY[4], 'planned', 'bg-yellow-100 text-yellow-800 border-yellow-200', 'medium', 1);
INSERT INTO tasks (title, description, type, category, date, month, year, time, assignee, assignees, status, color, priority, created_by) VALUES ('Atlas Navigator', 'Link: https://app.coschedule.com/calendar/413257/schedule/open/content/edit/7361883', 'Marketing', 'marketingOps', 8, 0, 2026, '09:00', 4, ARRAY[4], 'planned', 'bg-orange-100 text-orange-800 border-orange-200', 'medium', 1);
INSERT INTO tasks (title, description, type, category, date, month, year, time, assignee, assignees, status, color, priority, created_by) VALUES ('Veteran Family Summit - Registration #3', 'Link: https://app.coschedule.com/calendar/413257/schedule/open/content/edit/7251812', 'Marketing', 'marketingOps', 7, 0, 2026, '09:00', 4, ARRAY[4], 'planned', 'bg-yellow-100 text-yellow-800 border-yellow-200', 'medium', 1);
INSERT INTO tasks (title, description, type, category, date, month, year, time, assignee, assignees, status, color, priority, created_by) VALUES ('Veteran Family Summit', 'Link: https://app.coschedule.com/calendar/413257/schedule/open/content/edit/7251802', 'Social', 'socialMedia', 7, 0, 2026, '09:00', 4, ARRAY[4], 'planned', 'bg-yellow-100 text-yellow-800 border-yellow-200', 'medium', 1);
INSERT INTO tasks (title, description, type, category, date, month, year, time, assignee, assignees, status, color, priority, created_by) VALUES ('In her words - Guylaine Lamoureux post', 'Link: https://app.coschedule.com/calendar/413257/schedule/open/content/edit/7632277', 'Social', 'socialMedia', 5, 0, 2026, '09:00', 4, ARRAY[4], 'planned', 'bg-yellow-100 text-yellow-800 border-yellow-200', 'medium', 1);
INSERT INTO tasks (title, description, type, category, date, month, year, time, assignee, assignees, status, color, priority, created_by) VALUES ('RCMP dialogue sessions - February dates', 'Link: https://app.coschedule.com/calendar/413257/schedule/open/content/edit/7288453', 'Social', 'socialMedia', 2, 0, 2026, '09:00', 4, ARRAY[4], 'planned', 'bg-yellow-100 text-yellow-800 border-yellow-200', 'medium', 1);
INSERT INTO tasks (title, description, type, category, date, month, year, time, assignee, assignees, status, color, priority, created_by) VALUES ('Atlas Navigator', 'Link: https://app.coschedule.com/calendar/413257/schedule/open/content/edit/7452871', 'Marketing', 'marketingOps', 1, 0, 2026, '09:00', 4, ARRAY[4], 'planned', 'bg-orange-100 text-orange-800 border-orange-200', 'medium', 1);
INSERT INTO tasks (title, description, type, category, date, month, year, time, assignee, assignees, status, color, priority, created_by) VALUES ('Veteran Family Summit', 'Link: https://app.coschedule.com/calendar/413257/schedule/open/content/edit/7251798', 'Social', 'socialMedia', 30, 11, 2025, '09:00', 4, ARRAY[4], 'planned', 'bg-yellow-100 text-yellow-800 border-yellow-200', 'medium', 1);
INSERT INTO tasks (title, description, type, category, date, month, year, time, assignee, assignees, status, color, priority, created_by) VALUES ('Holiday campaign: NORAD', 'Link: https://app.coschedule.com/calendar/413257/schedule/open/content/edit/7556371', 'Social', 'socialMedia', 24, 11, 2025, '09:00', 4, ARRAY[4], 'planned', 'bg-green-100 text-green-800 border-green-200', 'medium', 1);
INSERT INTO tasks (title, description, type, category, date, month, year, time, assignee, assignees, status, color, priority, created_by) VALUES ('Holiday campaign: Marcia Chafe', 'Link: https://app.coschedule.com/calendar/413257/schedule/open/content/edit/7556355', 'Social', 'socialMedia', 23, 11, 2025, '09:00', 4, ARRAY[4], 'planned', 'bg-green-100 text-green-800 border-green-200', 'medium', 1);
INSERT INTO tasks (title, description, type, category, date, month, year, time, assignee, assignees, status, color, priority, created_by) VALUES ('Veteran Family Summit', 'Link: https://app.coschedule.com/calendar/413257/schedule/open/content/edit/7251795', 'Social', 'socialMedia', 22, 11, 2025, '09:00', 4, ARRAY[4], 'planned', 'bg-yellow-100 text-yellow-800 border-yellow-200', 'medium', 1);
INSERT INTO tasks (title, description, type, category, date, month, year, time, assignee, assignees, status, color, priority, created_by) VALUES ('Veteran Family Summit', 'Link: https://app.coschedule.com/calendar/413257/schedule/open/content/edit/7251790', 'Social', 'socialMedia', 19, 11, 2025, '09:00', 4, ARRAY[4], 'planned', 'bg-yellow-100 text-yellow-800 border-yellow-200', 'medium', 1);
INSERT INTO tasks (title, description, type, category, date, month, year, time, assignee, assignees, status, color, priority, created_by) VALUES ('Holiday message', 'Link: https://app.coschedule.com/calendar/413257/schedule/open/content/edit/7635936', 'Marketing', 'marketingOps', 19, 11, 2025, '09:00', 4, ARRAY[4], 'planned', 'bg-red-100 text-red-800 border-red-200', 'medium', 1);
INSERT INTO tasks (title, description, type, category, date, month, year, time, assignee, assignees, status, color, priority, created_by) VALUES ('Holiday campaign: Coping', 'Link: https://app.coschedule.com/calendar/413257/schedule/open/content/edit/7556360', 'Social', 'socialMedia', 18, 11, 2025, '09:00', 4, ARRAY[4], 'planned', 'bg-green-100 text-green-800 border-green-200', 'medium', 1);
INSERT INTO tasks (title, description, type, category, date, month, year, time, assignee, assignees, status, color, priority, created_by) VALUES ('In her words - Shauna Mulligan post', 'Link: https://app.coschedule.com/calendar/413257/schedule/open/content/edit/7632276', 'Social', 'socialMedia', 17, 11, 2025, '09:00', 4, ARRAY[4], 'planned', 'bg-yellow-100 text-yellow-800 border-yellow-200', 'medium', 1);
INSERT INTO tasks (title, description, type, category, date, month, year, time, assignee, assignees, status, color, priority, created_by) VALUES ('Holiday campaign: Danielle Kelly ', 'Link: https://app.coschedule.com/calendar/413257/schedule/open/content/edit/7556353', 'Social', 'socialMedia', 16, 11, 2025, '09:00', 4, ARRAY[4], 'planned', 'bg-green-100 text-green-800 border-green-200', 'medium', 1);
INSERT INTO tasks (title, description, type, category, date, month, year, time, assignee, assignees, status, color, priority, created_by) VALUES ('Veteran Family Summit ', 'Link: https://app.coschedule.com/calendar/413257/schedule/open/content/edit/7251797', 'Social', 'socialMedia', 15, 11, 2025, '09:00', 4, ARRAY[4], 'planned', 'bg-yellow-100 text-yellow-800 border-yellow-200', 'medium', 1);
INSERT INTO tasks (title, description, type, category, date, month, year, time, assignee, assignees, status, color, priority, created_by) VALUES ('Holiday campaign: supporting kids', 'Link: https://app.coschedule.com/calendar/413257/schedule/open/content/edit/7556352', 'Social', 'socialMedia', 12, 11, 2025, '09:00', 4, ARRAY[4], 'planned', 'bg-green-100 text-green-800 border-green-200', 'medium', 1);
INSERT INTO tasks (title, description, type, category, date, month, year, time, assignee, assignees, status, color, priority, created_by) VALUES ('Veteran Family Summit', 'Link: https://app.coschedule.com/calendar/413257/schedule/open/content/edit/7251788', 'Social', 'socialMedia', 11, 11, 2025, '09:00', 4, ARRAY[4], 'planned', 'bg-yellow-100 text-yellow-800 border-yellow-200', 'medium', 1);
INSERT INTO tasks (title, description, type, category, date, month, year, time, assignee, assignees, status, color, priority, created_by) VALUES ('16 days of activism: IPV 2', 'Link: https://app.coschedule.com/calendar/413257/schedule/open/content/edit/7606834', 'Social', 'socialMedia', 10, 11, 2025, '09:00', 4, ARRAY[4], 'planned', 'bg-yellow-100 text-yellow-800 border-yellow-200', 'medium', 1);
INSERT INTO tasks (title, description, type, category, date, month, year, time, assignee, assignees, status, color, priority, created_by) VALUES ('Holiday campaign: Polly''s video', 'Link: https://app.coschedule.com/calendar/413257/schedule/open/content/edit/7556350', 'Social', 'socialMedia', 8, 11, 2025, '09:00', 4, ARRAY[4], 'planned', 'bg-green-100 text-green-800 border-green-200', 'medium', 1);
INSERT INTO tasks (title, description, type, category, date, month, year, time, assignee, assignees, status, color, priority, created_by) VALUES ('16 days of activism: MST coping and healing', 'Link: https://app.coschedule.com/calendar/413257/schedule/open/content/edit/7606833', 'Social', 'socialMedia', 7, 11, 2025, '09:00', 4, ARRAY[4], 'planned', 'bg-yellow-100 text-yellow-800 border-yellow-200', 'medium', 1);
INSERT INTO tasks (title, description, type, category, date, month, year, time, assignee, assignees, status, color, priority, created_by) VALUES ('Atlas Navigator', 'Link: https://app.coschedule.com/calendar/413257/schedule/open/content/edit/7556342', 'Social', 'socialMedia', 6, 11, 2025, '09:00', 4, ARRAY[4], 'planned', 'bg-green-100 text-green-800 border-green-200', 'medium', 1);
INSERT INTO tasks (title, description, type, category, date, month, year, time, assignee, assignees, status, color, priority, created_by) VALUES ('Veteran Family Summit', 'Day 2 speakers

Link: https://app.coschedule.com/calendar/413257/schedule/open/content/edit/7572119', 'Social', 'socialMedia', 5, 11, 2025, '09:00', 4, ARRAY[4], 'planned', 'bg-yellow-100 text-yellow-800 border-yellow-200', 'medium', 1);
INSERT INTO tasks (title, description, type, category, date, month, year, time, assignee, assignees, status, color, priority, created_by) VALUES ('Veteran Family Summit', 'Day 2 speakers

Link: https://app.coschedule.com/calendar/413257/schedule/open/content/edit/7571585', 'Social', 'socialMedia', 5, 11, 2025, '09:00', 4, ARRAY[4], 'planned', 'bg-yellow-100 text-yellow-800 border-yellow-200', 'medium', 1);
INSERT INTO tasks (title, description, type, category, date, month, year, time, assignee, assignees, status, color, priority, created_by) VALUES ('Holiday campaign: Holiday stress video', 'Link: https://app.coschedule.com/calendar/413257/schedule/open/content/edit/7556348', 'Social', 'socialMedia', 4, 11, 2025, '09:00', 4, ARRAY[4], 'planned', 'bg-green-100 text-green-800 border-green-200', 'medium', 1);
INSERT INTO tasks (title, description, type, category, date, month, year, time, assignee, assignees, status, color, priority, created_by) VALUES ('Atlas Navigator', 'Link: https://app.coschedule.com/calendar/413257/schedule/open/content/edit/7361873', 'Marketing', 'marketingOps', 4, 11, 2025, '09:00', 4, ARRAY[4], 'planned', 'bg-orange-100 text-orange-800 border-orange-200', 'medium', 1);
INSERT INTO tasks (title, description, type, category, date, month, year, time, assignee, assignees, status, color, priority, created_by) VALUES ('Atlas Navigator', 'Link: https://app.coschedule.com/calendar/413257/schedule/open/content/edit/7375903', 'Marketing', 'marketingOps', 4, 11, 2025, '09:00', 4, ARRAY[4], 'planned', 'bg-orange-100 text-orange-800 border-orange-200', 'medium', 1);
INSERT INTO tasks (title, description, type, category, date, month, year, time, assignee, assignees, status, color, priority, created_by) VALUES ('16 days of activism: MST health care providers', 'Link: https://app.coschedule.com/calendar/413257/schedule/open/content/edit/7606828', 'Social', 'socialMedia', 3, 11, 2025, '09:00', 4, ARRAY[4], 'planned', 'bg-yellow-100 text-yellow-800 border-yellow-200', 'medium', 1);
INSERT INTO tasks (title, description, type, category, date, month, year, time, assignee, assignees, status, color, priority, created_by) VALUES ('Cannabis study social promo', 'Link: https://app.coschedule.com/calendar/413257/schedule/open/content/edit/7586666', 'Social', 'socialMedia', 3, 11, 2025, '09:00', 4, ARRAY[4], 'planned', 'bg-yellow-100 text-yellow-800 border-yellow-200', 'medium', 1);
INSERT INTO tasks (title, description, type, category, date, month, year, time, assignee, assignees, status, color, priority, created_by) VALUES ('Veteran Family Summit', 'Day 1 speakers

Link: https://app.coschedule.com/calendar/413257/schedule/open/content/edit/7571787', 'Social', 'socialMedia', 2, 11, 2025, '09:00', 4, ARRAY[4], 'planned', 'bg-yellow-100 text-yellow-800 border-yellow-200', 'medium', 1);
INSERT INTO tasks (title, description, type, category, date, month, year, time, assignee, assignees, status, color, priority, created_by) VALUES ('Veteran Family Summit', 'Day 1 speakers

Link: https://app.coschedule.com/calendar/413257/schedule/open/content/edit/7251784', 'Social', 'socialMedia', 2, 11, 2025, '09:00', 4, ARRAY[4], 'planned', 'bg-yellow-100 text-yellow-800 border-yellow-200', 'medium', 1);
INSERT INTO tasks (title, description, type, category, date, month, year, time, assignee, assignees, status, color, priority, created_by) VALUES ('In her words - Sarah Lefurgey post', 'Link: https://app.coschedule.com/calendar/413257/schedule/open/content/edit/7632274', 'Social', 'socialMedia', 1, 11, 2025, '09:00', 4, ARRAY[4], 'planned', 'bg-yellow-100 text-yellow-800 border-yellow-200', 'medium', 1);
INSERT INTO tasks (title, description, type, category, date, month, year, time, assignee, assignees, status, color, priority, created_by) VALUES ('Holiday campaign: Video from Jeanette', 'Link: https://app.coschedule.com/calendar/413257/schedule/open/content/edit/7514953', 'Social', 'socialMedia', 1, 11, 2025, '09:00', 4, ARRAY[4], 'planned', 'bg-green-100 text-green-800 border-green-200', 'medium', 1);
INSERT INTO tasks (title, description, type, category, date, month, year, time, assignee, assignees, status, color, priority, created_by) VALUES ('16 days of activism: IPV + holidays', 'Link: https://app.coschedule.com/calendar/413257/schedule/open/content/edit/7606825', 'Social', 'socialMedia', 29, 10, 2025, '09:00', 4, ARRAY[4], 'planned', 'bg-yellow-100 text-yellow-800 border-yellow-200', 'medium', 1);
INSERT INTO tasks (title, description, type, category, date, month, year, time, assignee, assignees, status, color, priority, created_by) VALUES ('Workshop promo', 'Link: https://app.coschedule.com/calendar/413257/schedule/open/content/edit/7660518', 'Social', 'socialMedia', 27, 10, 2025, '09:00', 4, ARRAY[4], 'planned', 'bg-yellow-100 text-yellow-800 border-yellow-200', 'medium', 1);
INSERT INTO tasks (title, description, type, category, date, month, year, time, assignee, assignees, status, color, priority, created_by) VALUES ('Perspectives/MBtM Email', 'Link: https://app.coschedule.com/calendar/413257/schedule/open/content/edit/7556058', 'Marketing', 'marketingOps', 27, 10, 2025, '09:00', 4, ARRAY[4], 'planned', 'bg-red-100 text-red-800 border-red-200', 'medium', 1);
INSERT INTO tasks (title, description, type, category, date, month, year, time, assignee, assignees, status, color, priority, created_by) VALUES ('MBtM Ep 33: Ryan Carey (TBI)', 'Link: https://app.coschedule.com/calendar/413257/schedule/open/content/edit/7556053', 'Blog', 'blogPosts', 27, 10, 2025, '09:00', 4, ARRAY[4], 'planned', 'bg-yellow-100 text-yellow-800 border-yellow-200', 'medium', 1);
INSERT INTO tasks (title, description, type, category, date, month, year, time, assignee, assignees, status, color, priority, created_by) VALUES ('Veteran Family Summit - Reminder #2', 'Link: https://app.coschedule.com/calendar/413257/schedule/open/content/edit/7251808', 'Marketing', 'marketingOps', 26, 10, 2025, '09:00', 4, ARRAY[4], 'planned', 'bg-yellow-100 text-yellow-800 border-yellow-200', 'medium', 1);
INSERT INTO tasks (title, description, type, category, date, month, year, time, assignee, assignees, status, color, priority, created_by) VALUES ('Veteran Family Summit', 'Registration reminder

Link: https://app.coschedule.com/calendar/413257/schedule/open/content/edit/7251761', 'Social', 'socialMedia', 26, 10, 2025, '09:00', 4, ARRAY[4], 'planned', 'bg-yellow-100 text-yellow-800 border-yellow-200', 'medium', 1);
INSERT INTO tasks (title, description, type, category, date, month, year, time, assignee, assignees, status, color, priority, created_by) VALUES ('Veteran Family Summit 2026 - November registration reminder - EN', 'Link: https://app.coschedule.com/calendar/413257/schedule/open/content/edit/7665614', 'Marketing', 'marketingOps', 26, 10, 2025, '09:00', 4, ARRAY[4], 'planned', 'bg-gray-100 text-gray-800 border-gray-200', 'medium', 1);
INSERT INTO tasks (title, description, type, category, date, month, year, time, assignee, assignees, status, color, priority, created_by) VALUES ('International Day for Prevention of Violence Against Women: What is IPV', 'Link: https://app.coschedule.com/calendar/413257/schedule/open/content/edit/7606773', 'Social', 'socialMedia', 25, 10, 2025, '09:00', 4, ARRAY[4], 'planned', 'bg-yellow-100 text-yellow-800 border-yellow-200', 'medium', 1);
INSERT INTO tasks (title, description, type, category, date, month, year, time, assignee, assignees, status, color, priority, created_by) VALUES ('International Day for Prevention of Violence Against Women: What is MST', 'Link: https://app.coschedule.com/calendar/413257/schedule/open/content/edit/7514941', 'Social', 'socialMedia', 25, 10, 2025, '09:00', 4, ARRAY[4], 'planned', 'bg-yellow-100 text-yellow-800 border-yellow-200', 'medium', 1);
INSERT INTO tasks (title, description, type, category, date, month, year, time, assignee, assignees, status, color, priority, created_by) VALUES ('Holiday campaign: Hope in hand', 'Link: https://app.coschedule.com/calendar/413257/schedule/open/content/edit/7514945', 'Social', 'socialMedia', 24, 10, 2025, '09:00', 4, ARRAY[4], 'planned', 'bg-yellow-100 text-yellow-800 border-yellow-200', 'medium', 1);
COMMIT;
SELECT 'Imported ' || (SELECT count(*) FROM tasks)::text || ' tasks.' as status;
